# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  ci:
    docker:
      - image: oven/bun:latest
    steps:
      - checkout
      - run:
          name: "install make"
          command: "apt update && apt install make tree"
      - run:
          name: "debug tree src"
          command: "ls -lah"
      - run:
          name: "build"
          command: "make build"
      - persist_to_workspace:
          root: .
          paths:
            - dist
  cd:
    docker:
      - image: cibuilds/aws:latest
    steps:
    - attach_workspace:
          at: .
    - run:
        name: Send dist to s3
        command: aws s3 sync ./dist s3://$AWS_BUCKET_NAME/ --delete
    - run:
        name: Invalidate Cloudfront cache
        command: aws cloudfront create-invalidation --distribution-id $AWS_DISTRIB_ID --paths "/*"

workflows:
  say-hello-workflow:
    when:
      and:
        - equal: [ circleci-project-setup, << pipeline.git.branch >>]
    jobs:
      - ci
  dev:
    when:
      and:
        - equal: [ dev, << pipeline.git.branch >>]
    jobs:
      - ci
  main:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >>]
    jobs:
      - ci
      - cd:
          requires:
                - ci
