# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  ci:
    docker:
      - image: oven/bun:latest
    steps:
      - checkout
      - restore_cache:
          name: "Restore yarn cache i exists"
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: "bun install"
          command: "bun install"
      - save_cache:
          name: "Save yarn cache"
          paths:
            - node_modules
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: "bun test"
          command: "bun test"
      - run:
          name: "bun build"
          command: "bun build"
      - persist_to_workspace:
          root: .
          paths:
            - dist
  cd:
    docker:
      - image: cibuilds/aws:latest
    steps:
    - attach_workspace:
          at: .
    - run:
        name: Send dist to s3
        command: aws s3 sync ./dist s3://$AWS_BUCKET_NAME/ --delete
    - run:
        name: Invalidate Cloudfront cache
        command: aws cloudfront create-invalidation --distribution-id $AWS_DISTRIB_ID --paths "/*"

workflows:
  say-hello-workflow:
    jobs:
      - ci
  dev:
    jobs:
      - ci
  main:
    jobs:
      - ci
      - cd:
          requires:
                - ci
